#!/usr/bin/python3

import sys
from pathlib import Path

ROOT_DIR = Path(__file__).parent.resolve()
sys.path.append(str(ROOT_DIR))

from src.main import main

if __name__ == "__main__":
    main(ROOT_DIR)
